#!/usr/bin/env bash

sudo apt-get update;
sudo apt-get install \
vim \
php7.0 \
nginx \
mysql-server \
php7.0-fpm \
php7.0-mysql \
nodejs \
npm \
mupen64plus \
minetest \
wine \
xaos \
gnome-terminal \
fceux \
screenfetch \
git \
exfat-fuse \
exfat-utils \
keepass2 \
clang-3.9 \
