#!/usr/bin/env perl

# run all environment setup scripts (target os: ubuntu)

use v5.10;

# underscore name of current operation
sub underscore {
	for(my $j = 0; $j < $_[0]; $j++)
	{
		print "=";
	}
	print "\n";
}

while(<setup-scripts/*>)
{
	my $msgPrefix = "Running script:";
	my $uscoreLength = (length $msgPrefix) + (length $_) + 1;

	# clearly name script running
	underscore($uscoreLength);
	print "$msgPrefix $_\n";
	underscore($uscoreLength);
	print "\n";
	
	# exec script
	system("./$_");

	# mark finished execution (successful or not, in case of no stdout)
	print "\n";
	underscore(length "Done.");
	print "Done.\n";
	underscore(length "Done.");
}
