#!/usr/bin/env bash

# config global git username and email
echo Setting global git username and email:
git config --global user.name "Matthew Connelly"
git config --global user.email matthew.b.connelly@gmail.com

echo ""
echo Confirming global username and email have been set:
echo ""

echo git config --global user.name:
git config --global user.name

echo git config --global user.email
git config --global user.email
