#!/usr/bin/env bash

WORKINGDIR=`pwd`
SYMLINK="sudo ln -s"
EXECDIR="/usr/local/bin"

cd user-scripts;
for f in *
do
echo Linking $f to $EXECDIR:
$SYMLINK $WORKINGDIR/user-scripts/$f $EXECDIR/
echo ""
done
