#!/usr/bin/env bash

echo Linking nodejs to /usr/bin as node:
sudo ln -s /usr/bin/nodejs /usr/bin/node
echo ""

echo Installing node modules with elevated permissions to /usr/local/bin:
sudo npm install -g \
gulp \
http-server \
html5-boilerplate \
