#!/usr/bin/env bash

brew update;
brew install \
htop \
transmission \
screenfetch \
node \
cowsay \
cmatrix \
caskroom/cask/libreoffice \
wget \
caskroom/cask/thunderbird \
caskroom/cask/iterm2 \
caskroom/cask/xquartz \
caskroom/cask/wine-stable \
caskroom/cask/keepassx \
caskroom/cask/insomniax \
caskroom/cask/vlc \
caskroom/cask/xaos \
ranger \
markdown \
